apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: root-resources-dev
  namespace: argocd
spec:
  project: applications

  source:
    repoURL: https://github.com/trongbiglab/gitops
    targetRevision: main
    path: resources
    directory:
      recurse: true

  destination:
    server: https://kubernetes.default.svc
    namespace: argocd  
  syncPolicy:
    automated:
      prune: true
      selfHeal: true