apiVersion: argoproj.io/v1alpha1
kind: AppProject
metadata:
  name: infra-systems
  namespace: argocd
spec:
  description: "Infra apps (kapenter, harbor,...)"

  sourceRepos:
    # Repo chứa Helm Charts (bao gồm cả các repo đang comment)
    - 'public.ecr.aws/karpenter/*'
    - 'https://aws.github.io/eks-charts'
    - 'https://kubernetes-sigs.github.io/aws-ebs-csi-driver'
    - 'https://charts.external-secrets.io'
    - 'https://helm.goharbor.io'
    - 'https://SonarSource.github.io/helm-chart-sonarqube'
    - 'https://charts.konghq.com'
    - 'https://raw.githubusercontent.com/kubernetes-csi/csi-driver-nfs/*'
    
    # Repo chứa cấu hình values (GitOps repo)
    - 'https://github.com/trongbiglab/gitops'

  destinations:
    - namespace: '*'
      server: https://kubernetes.default.svc

  clusterResourceWhitelist:
    - group: '*'
      kind: '*'