# 1. TargetGroupBinding cho Kong Proxy (Traffic người dùng)
apiVersion: elbv2.k8s.aws/v1beta1
kind: TargetGroupBinding
metadata:
  name: kong-proxy-tgb
  namespace: kong
spec:
  # Thay ARN của TG cho Proxy (Port 80/8000)
  targetGroupARN: arn:aws:elasticloadbalancing:ap-northeast-2:993839006183:targetgroup/kong-proxy-tg/9d4ee845c07b129b
  targetType: ip
  serviceRef:
    name: kong-gateway-kong-proxy # Tên service mặc định của helm
    port: 8000
---
# 2. TargetGroupBinding cho Admin API (kong-admin-api.trongduong.space)
apiVersion: elbv2.k8s.aws/v1beta1
kind: TargetGroupBinding
metadata:
  name: kong-admin-api-tgb
  namespace: kong
spec:
  # Thay ARN của TG cho Admin API (Port 8001)
  targetGroupARN: arn:aws:elasticloadbalancing:ap-northeast-2:993839006183:targetgroup/kong-admin-tg/2e2ff11d068c84a9
  targetType: ip
  serviceRef:
    name: kong-gateway-kong-admin
    port: 8001
---
# 3. TargetGroupBinding cho Kong Manager (kong-manager.trongduong.space)
apiVersion: elbv2.k8s.aws/v1beta1
kind: TargetGroupBinding
metadata:
  name: kong-manager-tgb
  namespace: kong
spec:
  # Thay ARN của TG cho Manager (Port 8002)
  targetGroupARN: arn:aws:elasticloadbalancing:ap-northeast-2:993839006183:targetgroup/kong-manager-tg/300a0f01db689a36
  targetType: ip
  serviceRef:
    name: kong-gateway-kong-manager
    port: 8002