apiVersion: elbv2.k8s.aws/v1beta1
kind: TargetGroupBinding
metadata:
  name: kong-proxy
  namespace: kong
spec:
  targetGroupARN: arn:aws:elasticloadbalancing:ap-northeast-2:980921740481:targetgroup/kong-tg/2420686c3de8adc9
  targetType: ip
  serviceRef:
    name: kong-kong-proxy
    port: 8000