apiVersion: karpenter.k8s.aws/v1
kind: EC2NodeClass
metadata:
  name: default
spec:
  amiFamily: AL2023
  amiSelectorTerms:
    - id: "ami-0f5484d170d4679c1"

  instanceProfile: "main-karpenter-node-role"

  subnetSelectorTerms:
    - tags:
        karpenter.sh/discovery: "main-cluster"

  securityGroupSelectorTerms:
    - tags:
        karpenter.sh/discovery: "main-cluster"

  metadataOptions:
    httpEndpoint: enabled
    httpTokens: required

  kubelet:
    podsPerCore: 20
    systemReserved:
      cpu: "200m"
      memory: "200Mi"
      ephemeral-storage: "1Gi"
    kubeReserved:
      cpu: "300m"
      memory: "300Mi"
      ephemeral-storage: "3Gi"
    cpuCFSQuota: true

    evictionHard:
      memory.available: "500Mi"
      nodefs.available: "10%"
      nodefs.inodesFree: "10%"
    evictionSoft:
      memory.available: "1Gi"
      nodefs.available: "15%"
      nodefs.inodesFree: "15%"
    evictionSoftGracePeriod:
      memory.available: 1m
      nodefs.available: 1m30s
      nodefs.inodesFree: 2m
    evictionMaxPodGracePeriod: 60