apiVersion: external-secrets.io/v1beta1
kind: ClusterSecretStore
metadata:
  name: cluster-secret-store
spec:
  provider:
    aws:
      service: SecretsManager
      region: ap-northeast-2
---
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: rds-db-credentials
  namespace: infra
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: cluster-secret-store
    kind: ClusterSecretStore
  target:
    name: rds-db-password # Tên Secret K8s sẽ tạo ra
    creationPolicy: Owner
  data:
  - secretKey: password
    remoteRef:
      # Thay bằng tên Secret thật của RDS trên Console (ví dụ: rds!db-85d...)
      key: rds!db-5a0289ff-c835-45ac-aebe-4c070ff34cb0
      property: password

---
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: kong-rds-secret
  namespace: kong
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: cluster-secret-store
    kind: ClusterSecretStore
  target:
    name: rds-kong-secret 
    creationPolicy: Owner
  data:
  - secretKey: password
    remoteRef:
      key: rds!db-5a0289ff-c835-45ac-aebe-4c070ff34cb0
      property: password
---
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: backend-rds-secret
  namespace: shopnow 
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: cluster-secret-store
    kind: ClusterSecretStore
  target:
    name: rds-db-password 
    creationPolicy: Owner
  data:
  - secretKey: password 
    remoteRef:
      key: rds!db-5a0289ff-c835-45ac-aebe-4c070ff34cb0 
      property: password